- name: Perform all Red Hat platform tasks
  debug:
    msg: Perform all Red Hat platform tasks
- debug:
    msg: "test"

- name: Ensure Apache is installed
  yum:
    name: "httpd"
    state: present

